# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b774d64981091af49f454b34d0064f6235106e01fdb8c81e7ba3dc5e9c519b6fe2326f5c204b1a7a2dcfa32b8c2e2b0621d1d6229a10c9e05677781256ed815d

test:
  secret_key_base: 2dfcc6f34e3a0bd9ea8603194d35f04bf4fe866ce07c841dc60f53cb0990e6a5a191e38420339820244fc9b088790106d960762358a419635df12f3ec62fd635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
